// State and LGA data
export const statesData = {
  Kwara: [
    "Asa",
    "Baruten",
    "Edu",
    "Ekiti",
    "Ifelodun",
    "Ilorin East",
    "Ilorin South",
    "Ilorin West",
    "Irepodun",
    "Isin",
    "Kaiama",
    "Moro",
    "Offa",
    "Oke Ero",
    "Oyun",
    "Pategi",
  ],
  Kano: [
    "Ajingi",
    "Albasu",
    "Bagwai",
    "Bebeji",
    "Bichi",
    "Bunkure",
    "Dala",
    "Dambatta",
    "Dawakin Kudu",
    "Dawakin Tofa",
    "Doguwa",
    "Fagge",
    "Gabasawa",
    "Garko",
    "Garun Mallam",
    "Gaya",
    "Gezawa",
    "Gwale",
    "Gwarzo",
    "Kabo",
    "Kano Municipal",
    "Karaye",
    "Kibiya",
    "Kiru",
    "Kumbotso",
    "Kunchi",
    "Kura",
    "Madobi",
    "Makoda",
    "Minjibir",
    "Nasarawa",
    "Rano",
    "Rimin Gado",
    "Rogo",
    "Shanono",
    "Sumaila",
    "Takai",
    "Tarauni",
    "Tofa",
    "Tsanyawa",
    "Tudun Wada",
    "Ungogo",
    "Warawa",
    "Wudil",
  ],
  Nasarawa: [
    "Akwanga",
    "Awe",
    "Doma",
    "Karu",
    "Keana",
    "Keffi",
    "Kokona",
    "Lafia",
    "Nasarawa",
    "Nasarawa Egon",
    "Obi",
    "Toto",
    "Wamba",
  ],
  Lagos: [
    "Agege",
    "Ajeromi-Ifelodun",
    "Alimosho",
    "Amuwo-Odofin",
    "Apapa",
    "Badagry",
    "Epe",
    "Eti Osa",
    "Ibeju-Lekki",
    "Ifako-Ijaiye",
    "Ikeja",
    "Ikorodu",
    "Kosofe",
    "Lagos Island",
    "Lagos Mainland",
    "Mushin",
    "Ojo",
    "Oshodi-Isolo",
    "Shomolu",
    "Surulere",
  ],
};

// Product types
export const productTypes = {
  A: "Tiró/Kohl (Unregistered)",
  B: "Ceremonial Powder (Unregistered)",
  C: "Branded Cosmetic 1 (Registered)",
  D: "Branded Cosmetic 2 (Registered)",
  E: "Branded Cosmetic 3 (Registered)",
};

// Vendor types
export const vendorTypes = [
  "Street Vendor",
  "Market Stall",
  "Retail Shop",
  "Pharmacy",
  "Supermarket",
  "Beauty Store",
];

// Chart colors
export const COLORS = ["#10b981", "#3b82f6", "#8b5cf6", "#f59e0b", "#ef4444"];

// Initial sample data
export const initialSamples = [
  {
    id: "KW-ILW-A-01-20251012",
    state: "Kwara",
    lga: "Ilorin West",
    productType: "A",
    productName: "Tiró Kohl",
    brand: "Local Brand",
    registered: false,
    market: "Oja Oba Market",
    vendorType: "Street Vendor",
    price: 500,
    leadLevel: 8500,
    status: "contaminated",
    date: "2025-10-12",
    coordinates: { lat: 8.4799, lng: 4.5418 },
    productPhoto: null,
    vendorPhoto: null,
    collectedBy: "Admin User",
  },
  {
    id: "KN-MUN-C-05-20251015",
    state: "Kano",
    lga: "Municipal",
    productType: "C",
    productName: "Face Powder Premium",
    brand: "BeautyGlow",
    registered: true,
    market: "Kurmi Market",
    vendorType: "Retail Shop",
    price: 2500,
    leadLevel: 150,
    status: "safe",
    date: "2025-10-15",
    coordinates: { lat: 12.0022, lng: 8.5919 },
    productPhoto: null,
    vendorPhoto: null,
    collectedBy: "Admin User",
  },
  {
    id: "LG-IKJ-B-03-20251018",
    state: "Lagos",
    lga: "Ikeja",
    productType: "B",
    productName: "Ceremonial Efun",
    brand: "N/A",
    registered: false,
    market: "Computer Village",
    vendorType: "Market Stall",
    price: 800,
    leadLevel: 12000,
    status: "contaminated",
    date: "2025-10-18",
    coordinates: { lat: 6.6018, lng: 3.3515 },
    productPhoto: null,
    vendorPhoto: null,
    collectedBy: "Admin User",
  },
  {
    id: "NS-KRF-D-02-20251010",
    state: "Nasarawa",
    lga: "Keffi",
    productType: "D",
    productName: "Makeup Foundation",
    brand: "GlamFace",
    registered: true,
    market: "Keffi Central Pharmacy",
    vendorType: "Pharmacy",
    price: 3500,
    leadLevel: 90,
    status: "safe",
    date: "2025-10-10",
    coordinates: { lat: 8.8481, lng: 7.8739 },
    productPhoto: null,
    vendorPhoto: null,
    collectedBy: "Admin User",
  },
];

// Initial users data
export const initialUsers = [
  {
    email: "admin@ledacap.ng",
    password: "admin123",
    name: "Admin User",
    role: "admin",
  },
];
